(define (square x) (* x x))

(define (tan-cf x k)
  (define (n i)
    (if (= i 1)
        x
        (* -1 (square x))))
  (define (d i) (- (* 2 i) 1))
  (define (cont-frac n d k)
    (define (frac-rec i)
      (if (= i k)
          (/ (n i)
             (d i))
          (/ (n i)
             (+ (d i) (frac-rec (+ i 1))))))
    (frac-rec 1))
  (cont-frac n d k))
